apiVersion: v2
name: nectar-freshdesk
description: A Helm chart for Nectar Freshdesk
type: application
version: 0.3.6
appVersion: 7e7bf2b
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.29.1
