{{- if .Values.gateway.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "nectar-freshdesk.fullname" . }}
  labels:
    {{- include "nectar-freshdesk.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "nectar-freshdesk.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      {{- with .Values.gateway.timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
