---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nectar-freshdesk.fullname" . }}
  labels:
    {{- include "nectar-freshdesk.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nectar-freshdesk.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
  ingress:
    - ports:
        - port: {{ .Values.service.port }}
