{{- if .Values.agent.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nectar-freshdesk.fullname" . }}-agent
  labels:
    {{- include "nectar-freshdesk.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.agent.pdb.minAvailable | default 0 }}
  selector:
    matchLabels:
      {{- include "nectar-freshdesk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
{{- end }}
