apiVersion: v1
kind: Service
metadata:
  name: {{ include "nectar-freshdesk.fullname" . }}
  labels:
    {{- include "nectar-freshdesk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nectar-freshdesk.selectorLabels" . | nindent 4 }}
